### ISSUE TITLE
xenhtml white out issue

### ISSUE THREAD

**Issue by Cyb3rNigga** [midnightchip/BetterSettings#8]
It seems to half fix itself when u select one and go back but that only lasts for I think a few seconds. https://imgur.com/gallery/ofOjFnU

**Comment by Mustafacydia** [comment]
I just talked to midnightchip about that and i came here to submit an issue

**Comment by Cyb3rNigga** [comment]
Oh 😂 the timing lol

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by midnightchip** [comment]
Im working on it, XEN appears to use a different version of UITable, and Im having an issue hooking it

**Comment by raydelvalle** [comment]
Trying updating libcolorpicker to v1.6.1
